# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [2]:
# YOUR CODE HERE

# First array containing only integer values
my_array1 = np.array([1, 2, 3, 4])
print(f"Array 1:\n{my_array1}\nShape: {my_array1.shape}, Type: {my_array1.dtype}")

# Second array containing a mix of integer and string values
my_array2 = np.array([4, "green", 37, "sjskaskna", "5"])
print(f"\nArray 2:\n{my_array2}\nShape: {my_array2.shape}, Type: {my_array2.dtype}")

# NumPy makes sure all the elements in the array have the same datatype, so this is of course integer for my_array1 (int64).
# my_array2 has 2 different data type values, so it converts all elements to string for uniformity (type <U21)


Array 1:
[1 2 3 4]
Shape: (4,), Type: int64

Array 2:
['4' 'green' '37' 'sjskaskna' '5']
Shape: (5,), Type: <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
# YOUR CODE HERE
# Numpy array
my_array3 = np.array([[1, 5, 10], [15,20,25]])
print(f"Array 3:\n{my_array3}\nShape: {my_array3.shape}, Size: {my_array3.size}, Type: {my_array3.dtype}")

# Size represents the total number of elements in the array

Array 3:
[[ 1  5 10]
 [15 20 25]]
Shape: (2, 3), Size: 6, Type: int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features.

Print the shape of the array.

In [4]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
# Tabular data layout
t_data = np.random.random((num_samples, num_features))
print(f"Shape of array: {t_data.shape}")

Shape of array: (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [5]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE
# Image data layout
i_data = np.random.random((num_images, num_rows, num_cols, num_channels))
print(f"Shape of array: {i_data.shape}")

Shape of array: (100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [6]:
# YOUR CODE HERE
# (3,2) numpy array:
my_array4 = np.array([[17,38], [52, 5], [7, 11]])
# 1.
print(f"Shape of the array: {my_array4.shape}")
# 2.
print(f"Sum of all elements: {my_array4.sum()}")
# 3.
print(f"Sum of elements by column: {my_array4.sum(axis=0)}")
# 4.
print(f"Sum of elements by row (as float): {my_array4.sum(axis=1).astype(float)}")
# 5.
print(f"First row: {my_array4[0]}")
# 6.
print(f"Second row: {my_array4[1]}")
# 7.
print(f"Element at position (1, 0): {my_array4[1, 0]}")
# 8.
my_array4[2, 1] = 10
print(f"Modified array:\n{my_array4}")
# 9.
print("Array elements:")
for element in np.nditer(my_array4):
    print(element)

Shape of the array: (3, 2)
Sum of all elements: 130
Sum of elements by column: [76 54]
Sum of elements by row (as float): [55. 57. 18.]
First row: [17 38]
Second row: [52  5]
Element at position (1, 0): 52
Modified array:
[[17 38]
 [52  5]
 [ 7 10]]
Array elements:
17
38
52
5
7
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [7]:
# YOUR CODE HERE
# 1:
pixel_vals = np.random.random((3, 2))
print(f"(3,2) numpy array of pixel values:\n{pixel_vals}\n")
# 2:
yearsRequested = np.arange(1991, 2018)
print(f"(27,) numpy array of years:\n{yearsRequested}\n")
# 3:
zero_array = np.zeros((3, 5, 10))
print(f"(3, 5, 10) numpy array of zeros:\n{zero_array}\n")
# 4:
one_array = np.ones((3, 5, 10))
print(f"(3, 5, 10) numpy array of ones:\n{one_array}\n")
# 5:
five_array = np.ones((3, 3)) * 5
print(f"Array with a constant value (5):\n{five_array}\n")
# 6:
rand_norm_dist_array = np.random.normal(0, 1, 10)
print(f"Array with random numbers from normal distribution:\n{rand_norm_dist_array}\n")


(3,2) numpy array of pixel values:
[[0.28999571 0.50818013]
 [0.47655793 0.57281228]
 [0.53403895 0.66869277]]

(27,) numpy array of years:
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]

(3, 5, 10) numpy array of zeros:
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]

(3, 5, 10) numpy array of ones:
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [8]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [11]:
# YOUR CODE HERE

# 1:
years_3d = years.reshape((3, 3, 3))
print(f"3D array (years_3d):\n{years_3d}\nShape: {years_3d.shape}\n")
# 2:
years_1d = years_3d.flatten()
print(f"1D array (years_1d):\n{years_1d}\nShape: {years_1d.shape}\n")
# 3:
years_2d = years_1d[np.newaxis, :]
print(f"2D array (years_2d):\n{years_2d}\nShape: {years_2d.shape}\n")
# 4:
years_1d_again = np.squeeze(years_2d, axis=0)
print(f"1D array (years_1d):\n{years_1d_again}\nShape: {years_1d_again.shape}")


3D array (years_3d):
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
Shape: (3, 3, 3)

1D array (years_1d):
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape: (27,)

2D array (years_2d):
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
Shape: (1, 27)

1D array (years_1d):
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
Shape: (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [15]:
# YOUR CODE HERE

# Examples using np.concatenate()

# 1. Concatenating 1D arrays along default axis:
array_1 = np.array([1, 2])
array_2 = np.array([2, 1])
print(f"1:\n{np.concatenate((array_1, array_2))}")

# 2. Concatenating 2D arrays along axis 0:
array_3 = np.array([[1, 2], [4, 8]])
array_4 = np.array([[16, 32], [64, 128]])
print(f"2:\n{np.concatenate((array_3, array_4), axis=0)}")

# 3. Concatenating 2D arrays along axis 1:
print(f"3:\n{np.concatenate((array_3, array_4), axis=1)}")

# 4. Concatenating 3D arrays along axis 2:
array_5 = np.random.random((2, 4, 6))
array_6 = np.random.random((2, 4, 6))
print(f"4:\n{np.concatenate((array_5, array_6), axis=2)}")

# Examples using np.stack()

# 1. Stacking 1D arrays above on default axis:
print(f"1:\n{np.stack((array_1,array_2))}")

# 2. Stacking 2D arrays above on default axis:
print(f"2:\n{np.stack((array_3,array_4))}")

# 3. Stacking 2D arrays above on axis 1:
print(f"3:\n{np.stack((array_3,array_4), axis=1)}")

# 4. Stacking 3D arrays above on axis 2:
print(f"4:\n{np.stack((array_5,array_6), axis=2)}")


1:
[1 2 2 1]
2:
[[  1   2]
 [  4   8]
 [ 16  32]
 [ 64 128]]
3:
[[  1   2  16  32]
 [  4   8  64 128]]
4:
[[[0.35354353 0.58715686 0.64911593 0.16244487 0.23872777 0.12908947
   0.98259119 0.75635266 0.84474699 0.84465883 0.04277737 0.90889542]
  [0.84284981 0.94262884 0.95039543 0.82807922 0.15788159 0.85140441
   0.28159142 0.70246461 0.07096768 0.8527092  0.27371577 0.60367746]
  [0.45614228 0.75017989 0.31063409 0.5042826  0.39619668 0.52472513
   0.82971078 0.87382325 0.74394213 0.45313367 0.15756392 0.49007212]
  [0.8812703  0.91023243 0.41204758 0.80021094 0.82660331 0.03153012
   0.23183434 0.74751703 0.01771938 0.63575321 0.48111255 0.60543398]]

 [[0.22125619 0.66340691 0.67361211 0.36070501 0.6362283  0.07735934
   0.08603418 0.42883772 0.7625636  0.18549162 0.05759208 0.60325052]
  [0.99468216 0.47791182 0.08019933 0.30393191 0.90942602 0.78260115
   0.36048459 0.74298579 0.36609672 0.1611367  0.4221189  0.77239536]
  [0.55261666 0.31239778 0.41872193 0.49488037 0.19631618 

---
#### <span style="color:chocolate">Numpy broadcasting</span>

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [16]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [17]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [18]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [19]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [20]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.45102794, 0.78001688, 0.3805665 , 0.92455946],
       [0.58596166, 0.59393691, 0.5562861 , 0.30213463],
       [0.19538147, 0.65703229, 0.48165841, 0.93478967],
       [0.68428764, 0.09074412, 0.87486992, 0.69911098],
       [0.75810387, 0.13179992, 0.73931009, 0.2134566 ],
       [0.01380833, 0.0723283 , 0.93032944, 0.63753396],
       [0.92615431, 0.12648165, 0.85121036, 0.37766568],
       [0.78959715, 0.77076385, 0.17782148, 0.32149885],
       [0.15789916, 0.2008389 , 0.52501348, 0.85360888],
       [0.29841463, 0.98516275, 0.46609103, 0.09164694]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [21]:
# YOUR CODE HERE

# 1:
means = np.mean(my_array, axis=0, keepdims=True)
stds = np.std(my_array, axis=0, keepdims=True)
print('\nColumn means:\n', means)
print('Column stds:\n', stds)

# 2:
standardized = (my_array - means/stds)
print('\nStandardized array:\n', standardized)
print('Standardized array shape:', standardized.shape)



Column means:
 [[0.48606362 0.44091056 0.59831568 0.53560057]]
Column stds:
 [[0.29338429 0.33176063 0.23087065 0.29581366]]

Standardized array:
 [[-1.2057193  -0.54898518 -2.2109958  -0.88604176]
 [-1.07078558 -0.73506515 -2.0352762  -1.50846659]
 [-1.46136577 -0.67196978 -2.10990389 -0.87581155]
 [-0.97245961 -1.23825794 -1.71669238 -1.11149023]
 [-0.89864338 -1.19720214 -1.85225221 -1.59714462]
 [-1.64293892 -1.25667376 -1.66123285 -1.17306726]
 [-0.73059294 -1.20252041 -1.74035194 -1.43293553]
 [-0.86715009 -0.55823821 -2.41374082 -1.48910236]
 [-1.49884809 -1.12816317 -2.06654881 -0.95699233]
 [-1.35833262 -0.34383932 -2.12547126 -1.71895427]]
Standardized array shape: (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [25]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [32]:
# YOUR CODE HERE

# 1.
border_crop = my_image[1:-1, 1:-1]
print("\nImage cropped with a border of size 1:\n", border_crop)

# 2.
crop_2 = my_image[2:-2, 2:-2]
print("\nImage cropped by removing first and last two rows/columns:\n", crop_2)

# 3.
reversed_columns = my_image[:, ::-1]
print("\nImage with reversed column order:\n", reversed_columns)

# 4. I don't really understand instructions but this is my guess:
mod_image = my_image.copy()
mod_image[mod_image % 2 == 0] = 0.5
print("\nImage with elements divisible by 2 set to 0.5:\n", mod_image)


Image cropped with a border of size 1:
 [[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]

Image cropped by removing first and last two rows/columns:
 [[0.48]]

Image with reversed column order:
 [[0.16 0.12 0.08 0.04 0.5 ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]

Image with elements divisible by 2 set to 0.5:
 [[0.5  0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]
